# Generated by Django 5.0 on 2023-12-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mytable',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
