# Generated by Django 5.0 on 2023-12-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
