# Generated by Django 5.0 on 2023-12-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsite', '0003_question_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
